CREATE SCHEMA IF NOT EXISTS BL_3NF;
 
CREATE SEQUENCE IF NOT EXISTS bl_3nf.ce_countries_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_3nf.ce_states_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_3nf.ce_cities_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_3nf.ce_streets_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_3nf.ce_addresses_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_3nf.ce_car_brands_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_3nf.ce_car_models_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_3nf.ce_cars_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_3nf.ce_employees_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_3nf.ce_dealers_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_3nf.ce_payment_methods_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_3nf.ce_sales_channels_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_3nf.ce_dates_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_3nf.ce_customers_sdc_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_3nf.ce_sales_seq START 1;
 
CREATE TABLE IF NOT EXISTS BL_3NF.CE_COUNTRIES (
    COUNTRY_ID INT PRIMARY KEY,
    COUNTRY_SRC_ID VARCHAR(100) NOT NULL,
    COUNTRY_NAME VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,       
    SOURCE_ENTITY VARCHAR(50) NOT NULL,       
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE
);
 
CREATE TABLE IF NOT EXISTS BL_3NF.CE_STATES (
    STATE_ID INT PRIMARY KEY,
    STATE_SRC_ID VARCHAR(100) NOT NULL,
    COUNTRY_ID INT NOT NULL REFERENCES BL_3NF.CE_COUNTRIES(COUNTRY_ID),
    STATE_NAME VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,       
    SOURCE_ENTITY VARCHAR(50) NOT NULL,       
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE,
    UNIQUE(COUNTRY_ID, STATE_NAME)
);
 
CREATE TABLE IF NOT EXISTS BL_3NF.CE_CITIES (
    CITY_ID INT PRIMARY KEY,
    CITY_SRC_ID VARCHAR(100) NOT NULL,
    STATE_ID INT NOT NULL REFERENCES BL_3NF.CE_STATES(STATE_ID),
    CITY_NAME VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,       
    SOURCE_ENTITY VARCHAR(50) NOT NULL,       
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE,
    UNIQUE(STATE_ID, CITY_NAME)
);
 
 
CREATE TABLE IF NOT EXISTS BL_3NF.CE_STREETS (
    STREET_ID INT PRIMARY KEY,
    STREET_SRC_ID VARCHAR(100) NOT NULL,
    CITY_ID INT NOT NULL REFERENCES BL_3NF.CE_CITIES(CITY_ID),
    STREET_NAME VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,       
    SOURCE_ENTITY VARCHAR(50) NOT NULL,       
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE,
    UNIQUE(CITY_ID, STREET_NAME)
);
 
CREATE TABLE IF NOT EXISTS BL_3NF.CE_ADDRESSES (
    ADDRESS_ID INT PRIMARY KEY,
    ADDRESS_SRC_ID VARCHAR(100) NOT NULL,
    STREET_ID INT NOT NULL REFERENCES BL_3NF.CE_STREETS(STREET_ID),
    BUILDING_NUMBER VARCHAR(20),
    POSTAL_CODE VARCHAR(20),
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,       
    SOURCE_ENTITY VARCHAR(50) NOT NULL,       
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE,
    UNIQUE(STREET_ID, BUILDING_NUMBER, POSTAL_CODE)
);
 
 CREATE TABLE IF NOT EXISTS BL_3NF.CE_CAR_BRANDS (
    CAR_BRAND_ID INT PRIMARY KEY,
    BRAND_SRC_ID VARCHAR(100) NOT NULL,
    BRAND_NAME VARCHAR(100) UNIQUE NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,       
    SOURCE_ENTITY VARCHAR(50) NOT NULL,       
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE
);
 
CREATE TABLE IF NOT EXISTS BL_3NF.CE_CAR_MODELS (
    CAR_MODEL_ID INT PRIMARY KEY,
    MODEL_SRC_ID VARCHAR(100) NOT NULL,
    CAR_BRAND_ID INT NOT NULL REFERENCES BL_3NF.CE_CAR_BRANDS(CAR_BRAND_ID),
    MODEL_NAME VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,       
    SOURCE_ENTITY VARCHAR(50) NOT NULL,       
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE,
    UNIQUE(CAR_BRAND_ID, MODEL_NAME)
);
 
CREATE TABLE IF NOT EXISTS BL_3NF.CE_CARS (
    CAR_ID INT PRIMARY KEY,
    CAR_SRC_ID VARCHAR(200) UNIQUE NOT NULL,
    CAR_MODEL_ID INT NOT NULL REFERENCES BL_3NF.CE_CAR_MODELS(CAR_MODEL_ID),
    YEAR INT, 
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,       
    SOURCE_ENTITY VARCHAR(50) NOT NULL,       
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE
);
 
CREATE TABLE IF NOT EXISTS BL_3NF.CE_EMPLOYEES (
    EMPLOYEE_ID INT PRIMARY KEY,
    EMPLOYEE_SRC_ID VARCHAR(100) NOT NULL,
    EMPLOYEE_FIRST_NAME VARCHAR(100),
    EMPLOYEE_LAST_NAME VARCHAR(100),
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,       
    SOURCE_ENTITY VARCHAR(50) NOT NULL,       
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE
);
 
CREATE TABLE IF NOT EXISTS BL_3NF.CE_DEALERS (
    DEALER_ID INT PRIMARY KEY,
    DEALER_SRC_ID VARCHAR(100) NOT NULL,
    DEALER_NAME VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,       
    SOURCE_ENTITY VARCHAR(50) NOT NULL,       
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE,
    UNIQUE(DEALER_NAME)
);
 
CREATE TABLE IF NOT EXISTS BL_3NF.CE_PAYMENT_METHODS (
    PAYMENT_METHOD_ID INT PRIMARY KEY,
    PAYMENT_METHOD_SRC_ID VARCHAR(100) NOT NULL,
    METHOD_NAME VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,       
    SOURCE_ENTITY VARCHAR(50) NOT NULL,       
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE,
    UNIQUE(METHOD_NAME)
);
 
CREATE TABLE IF NOT EXISTS BL_3NF.CE_SALES_CHANNELS (
    SALES_CHANNEL_ID INT PRIMARY KEY,
    SALES_CHANNEL_SRC_ID VARCHAR(100) NOT NULL,
    CHANNEL_NAME VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,       
    SOURCE_ENTITY VARCHAR(50) NOT NULL,       
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE,
    UNIQUE(CHANNEL_NAME)
);
 
CREATE TABLE IF NOT EXISTS BL_3NF.CE_DATES (
    DATE_ID INT PRIMARY KEY,
    DATE DATE UNIQUE NOT NULL,
    DAY INT,
    MONTH INT,
    YEAR INT,
    QUARTER INT,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,       
    SOURCE_ENTITY VARCHAR(50) NOT NULL,       
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE
);
 
CREATE TABLE IF NOT EXISTS BL_3NF.CE_CUSTOMERS_SDC (
    CUSTOMER_ID INT PRIMARY KEY,
    CUSTOMER_SRC_ID VARCHAR(300) NOT NULL,
    CUSTOMER_FIRST_NAME VARCHAR(100),
    CUSTOMER_LAST_NAME VARCHAR(100),
    CUSTOMER_EMAIL VARCHAR(100),
    CUSTOMER_TELEPHONE_NUMBER VARCHAR(30),
    ADDRESS_ID INT REFERENCES BL_3NF.CE_ADDRESSES(ADDRESS_ID),
    START_DT DATE NOT NULL,
    END_DT DATE,
    IS_ACTIVE CHAR(1) CHECK (IS_ACTIVE IN ('Y', 'N')),
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,       
    SOURCE_ENTITY VARCHAR(50) NOT NULL,       
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE
);
 
CREATE TABLE IF NOT EXISTS BL_3NF.CE_SALES (
    SALE_ID INT PRIMARY KEY,
    SALE_SRC_ID VARCHAR(50) NOT NULL, 
    SOURCE_ID VARCHAR(100) NOT NULL,
    CUSTOMER_ID INT REFERENCES BL_3NF.CE_CUSTOMERS_SDC(CUSTOMER_ID),
    EMPLOYEE_ID INT REFERENCES BL_3NF.CE_EMPLOYEES(EMPLOYEE_ID),
    CAR_ID INT REFERENCES BL_3NF.CE_CARS(CAR_ID),
    DEALER_ID INT REFERENCES BL_3NF.CE_DEALERS(DEALER_ID),
    DATE_ID INT REFERENCES BL_3NF.CE_DATES(DATE_ID),
    SALES_CHANNEL_ID INT REFERENCES BL_3NF.CE_SALES_CHANNELS(SALES_CHANNEL_ID),
    PAYMENT_METHOD_ID INT REFERENCES BL_3NF.CE_PAYMENT_METHODS(PAYMENT_METHOD_ID),
    SALE_PRICE DECIMAL(12, 2),
    COMMISSION_RATE DECIMAL(20, 18),
    COMMISSION_EARNED DECIMAL(12, 2),
    REDUCTION_PERCENT DECIMAL(5, 2),
    INCOME DECIMAL(12, 2),
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,       
    SOURCE_ENTITY VARCHAR(50) NOT NULL,       
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE
);