CREATE SCHEMA IF NOT EXISTS BL_DM;

CREATE SEQUENCE IF NOT EXISTS bl_dm.dim_dates_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_dm.dm_cars_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_dm.dim_dealers_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_dm.dim_payment_methods_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_dm.dim_sales_channels_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_dm.dim_customers_sdc_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_dm.dim_employees_seq START 1;
CREATE SEQUENCE IF NOT EXISTS bl_dm.fct_sales_seq START 1;

CREATE TABLE IF NOT EXISTS BL_DM.DIM_DATES (
    DATE_SURR_ID INT PRIMARY KEY, 
    DATE DATE NOT NULL UNIQUE,
    DAY INT,
    MONTH INT,
    YEAR INT,
    QUARTER INT,
    IS_WEEKEND CHAR(1),
    MONTH_NAME VARCHAR(20),
    DAY_OF_WEEK VARCHAR(20),
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE,
    SOURCE_SYSTEM VARCHAR(50),
    SOURCE_ENTITY VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS BL_DM.DIM_CARS (
    CAR_SURR_ID INT PRIMARY KEY,  
    CAR_SRC_ID VARCHAR(200) NOT NULL UNIQUE,
    BRAND_NAME VARCHAR(100),
    MODEL_NAME VARCHAR(100),
    YEAR INT,
    SOURCE_SYSTEM VARCHAR(50),
    SOURCE_ENTITY VARCHAR(50),
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS BL_DM.DIM_DEALERS (
    DEALER_SURR_ID INT PRIMARY KEY, 
    DEALER_SRC_ID VARCHAR(255) NOT NULL UNIQUE,
    DEALER_NAME VARCHAR(255) NOT NULL,
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE,
    SOURCE_SYSTEM VARCHAR(50),
    SOURCE_ENTITY VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS BL_DM.DIM_PAYMENT_METHODS (
    PAYMENT_METHOD_SURR_ID INT PRIMARY KEY, 
    PAYMENT_METHOD_SRC_ID VARCHAR(255) NOT NULL UNIQUE,
    METHOD_NAME VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50),
    SOURCE_ENTITY VARCHAR(50),
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS BL_DM.DIM_SALES_CHANNELS (
    SALES_CHANNEL_SURR_ID INT PRIMARY KEY,
    SALES_CHANNEL_SRC_ID VARCHAR(255) NOT NULL UNIQUE,
    CHANNEL_NAME VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50),
    SOURCE_ENTITY VARCHAR(50),
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS BL_DM.DIM_CUSTOMERS_SDC (
    CUSTOMER_SURR_ID INT PRIMARY KEY,  
    CUSTOMER_SRC_ID VARCHAR(300) NOT NULL,
    CUSTOMER_FIRST_NAME VARCHAR(100),
    CUSTOMER_LAST_NAME VARCHAR(100),
    CUSTOMER_EMAIL VARCHAR(100),
    CUSTOMER_TELEPHONE_NUMBER VARCHAR(30),
    CUSTOMER_COUNTRY VARCHAR(100),
    CUSTOMER_STATE VARCHAR(100),
    CUSTOMER_CITY VARCHAR(100),
    CUSTOMER_STREET_NAME VARCHAR(100),
    CUSTOMER_BUILDING_NUMBER VARCHAR(20),
    CUSTOMER_POSTAL_CODE VARCHAR(20),
    START_DT DATE NOT NULL,
    END_DT DATE,
    IS_ACTIVE CHAR(1) CHECK (IS_ACTIVE IN ('Y', 'N')),
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE,
    SOURCE_SYSTEM VARCHAR(50),
    SOURCE_ENTITY VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS BL_DM.DIM_EMPLOYEES (
    EMPLOYEE_SURR_ID INT PRIMARY KEY, 
    EMPLOYEE_SRC_ID VARCHAR(100) NOT NULL UNIQUE,
    EMPLOYEE_FIRST_NAME VARCHAR(100),
    EMPLOYEE_LAST_NAME VARCHAR(100),
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE,
    SOURCE_SYSTEM VARCHAR(50),
    SOURCE_ENTITY VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS BL_DM.FCT_SALES (
    SALE_SURR_ID INT,
    SALE_SRC_ID VARCHAR(50) NOT NULL,
    CUSTOMER_SURR_ID INT,
    EMPLOYEE_SURR_ID INT,
    CAR_SURR_ID INT,
    DEALER_SURR_ID INT,
    DATE_SURR_ID INT,
    PAYMENT_METHOD_SURR_ID INT,
    SALES_CHANNEL_SURR_ID INT,
    SALE_PRICE DECIMAL(12, 2),
    COMMISSION_RATE DECIMAL(20, 18),
    COMMISSION_EARNED DECIMAL(12, 2),
    REDUCTION_PERCENT DECIMAL(5, 2),
    INCOME DECIMAL(12, 2),
    CALC_DISCOUNT_VALUE DECIMAL(12, 2),
    CALC_COMMISSION_CHECK DECIMAL(12, 2),
    INSERT_DT DATE,
    UPDATE_DT DATE DEFAULT CURRENT_DATE,
    SOURCE_ID VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(50),
    SOURCE_ENTITY VARCHAR(50)
) PARTITION BY RANGE (DATE_SURR_ID);