-- 3NF
CALL BL_CL.LOAD_CE_COUNTRIES();
CALL BL_CL.LOAD_CE_STATES();
CALL BL_CL.LOAD_CE_CITIES();
CALL BL_CL.LOAD_CE_STREETS();
CALL BL_CL.LOAD_CE_ADDRESSES();
CALL BL_CL.LOAD_CE_CUSTOMERS_SDC(); 
CALL BL_CL.LOAD_CE_CAR_BRANDS();
CALL BL_CL.LOAD_CE_CAR_MODELS();
CALL BL_CL.LOAD_CE_CARS();
CALL BL_CL.LOAD_CE_EMPLOYEES();
CALL BL_CL.LOAD_CE_DEALERS();
CALL BL_CL.LOAD_CE_PAYMENT_METHODS();
CALL BL_CL.LOAD_CE_SALES_CHANNELS();
CALL BL_CL.LOAD_CE_DATES();
CALL BL_CL.LOAD_CE_SALES();

-- DM

CALL BL_CL.LOAD_DIM_DATES();
CALL BL_CL.LOAD_DIM_EMPLOYEES();
CALL BL_CL.LOAD_DIM_DEALERS();
CALL BL_CL.LOAD_DIM_CARS();
CALL BL_CL.LOAD_DIM_CUSTOMERS_SDC();
CALL BL_CL.LOAD_DIM_PAYMENT_METHODS();
CALL BL_CL.LOAD_DIM_SALES_CHANNELS();

CALL BL_CL.LOAD_FCT_SALES_DM_PARTITIONED(4500, 4593, 'BL_DM.FCT_SALES_2022_Q2');
CALL BL_CL.LOAD_FCT_SALES_DM_PARTITIONED(4594, 4686, 'BL_DM.FCT_SALES_2022_Q3');
CALL BL_CL.LOAD_FCT_SALES_DM_PARTITIONED(4687, 4776, 'BL_DM.FCT_SALES_2022_Q4');
CALL BL_CL.LOAD_FCT_SALES_DM_PARTITIONED(4777, 4867, 'BL_DM.FCT_SALES_2023_Q1');
CALL BL_CL.LOAD_FCT_SALES_DM_PARTITIONED(4868, 4958, 'BL_DM.FCT_SALES_2023_Q2');
CALL BL_CL.LOAD_FCT_SALES_DM_PARTITIONED(4959, 5050, 'BL_DM.FCT_SALES_2023_Q3');
CALL BL_CL.LOAD_FCT_SALES_DM_PARTITIONED(5051, 5142, 'BL_DM.FCT_SALES_2023_Q4');
CALL BL_CL.LOAD_FCT_SALES_DM_PARTITIONED(5143, 5234, 'BL_DM.FCT_SALES_2024_Q1');
CALL BL_CL.LOAD_FCT_SALES_DM_PARTITIONED(5235, 5299, 'BL_DM.FCT_SALES_2024_Q2');